books = [
    {
        "id": 1,
        "title": "Django By Example",
        "author": "Famous Guy",
        "publisher": "100pay Limited",
        "publisher_date": "2022-01-19",
        "page_count": 1000,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Flask Web Development",
        "author": "Miguel Grinberg",
        "publisher": "O'Reilly Media",
        "publisher_date": "2018-07-10",
        "page_count": 320,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "publisher_date": "2019-05-03",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "publisher": "Addison-Wesley",
        "publisher_date": "2015-03-13",
        "page_count": 256,
        "language": "English",
    },
    {
        "id": 5,
        "title": "Learning Python",
        "author": "Mark Lutz",
        "publisher": "O'Reilly Media",
        "publisher_date": "2013-07-06",
        "page_count": 1648,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "publisher_date": "2019-11-12",
        "page_count": 592,
        "language": "English",
    },
    {
        "id": 7,
        "title": "Deep Learning with Python",
        "author": "François Chollet",
        "publisher": "Manning Publications",
        "publisher_date": "2017-12-22",
        "page_count": 384,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "publisher_date": "2008-08-01",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 9,
        "title": "Python for Data Analysis",
        "author": "Wes McKinney",
        "publisher": "O'Reilly Media",
        "publisher_date": "2017-10-20",
        "page_count": 550,
        "language": "English",
    },
    {
        "id": 10,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "publisher_date": "2015-07-30",
        "page_count": 792,
        "language": "English",
    },
    {
        "id": 11,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt, David Thomas",
        "publisher": "Addison-Wesley",
        "publisher_date": "2019-09-13",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 12,
        "title": "Introduction to Machine Learning with Python",
        "author": "Andreas C. Müller, Sarah Guido",
        "publisher": "O'Reilly Media",
        "publisher_date": "2016-10-06",
        "page_count": 394,
        "language": "English",
    },
    {
        "id": 13,
        "title": "Test-Driven Development with Python",
        "author": "Harry J.W. Percival",
        "publisher": "O'Reilly Media",
        "publisher_date": "2014-06-27",
        "page_count": 624,
        "language": "English",
    },
    {
        "id": 14,
        "title": "The Art of Computer Programming",
        "author": "Donald E. Knuth",
        "publisher": "Addison-Wesley",
        "publisher_date": "1997-01-01",
        "page_count": 672,
        "language": "English",
    },
    {
        "id": 15,
        "title": "Python Tricks",
        "author": "Dan Bader",
        "publisher": "Dan Bader",
        "publisher_date": "2017-10-02",
        "page_count": 302,
        "language": "English",
    }
]
